### ISSUE TITLE
Cannot launch on MacOS

### ISSUE THREAD

**Issue by cakarlen** [Sumandora/tarasande#14]
OS: MacOS 13.5.2 (Ventura)
Arch: M1 (arm64)
Versions:
1. Minecraft 1.20.2
2. Fabric Loader 0.14.24
3. Fabric Kotlin 1.10.13+kotlin.1.9.20
4. Java 17.0.2
5. Gradle 8.4

After adding main mod with Fabric Kotlin using Prism Launcher, I get the following error upon launch:
<img width="963" alt="CleanShot 2023-11-12 at 21 09 50@2x" src="https://github.com/Sumandora/tarasande/assets/33635487/e2c6263f-501b-4026-9390-229d6e20753c">

Any ideas as to why this happens?

**Comment by Sumandora** [comment]
I do have some ideas, however I do not own macOS hardware, I would prefer if you would write me on Discord (My name: 48_8b_45_08) in order to do some more rapid testing.

**Comment by cakarlen** [comment]
I appreciate your help. I just sent a request to you.
