### ISSUE TITLE
❤️

### ISSUE THREAD

**Issue by Nxyi** [Sumandora/tarasande#15]
🐀

**Comment by Nxyi** [comment]
mb, wrong thing

**Comment by Sumandora** [comment]
Yes, of course the open source project is ratted. Not like you can literally see the code? Please think before commenting on the internet. Thanks in advance.

**Comment by Nxyi** [comment]
> Yes, of course the open source project is ratted. Not like you can literally see the code? Please think before commenting on the internet. Thanks in advance. 

I added a comment saying "mb, wrong thing" previously 👍 also why i closed the issue
