### ISSUE TITLE
Toggled every modules when press \ key

### ISSUE THREAD

**Issue by hiyama283** [Sumandora/tarasande#18]
Versioin: 1.20.4
Using Lunar client

**Comment by Sumandora** [comment]
Can't reproduce, more information is needed.

**Comment by hiyama283** [comment]
Cause found.
This problem was caused by the fact that the -1 key is recognised as -1, which means that it is not binded, but it is toggled without recognising that it is not binded.
Therefore, we advise you to add a statement before the switchState, such as 'continue' if bind.button is -1.

**Comment by Sumandora** [comment]
-1 represents a key not known by GLFW if your keyboard emits such a key either GLFW is at fault or your keyboard has serious issues. Either way this is not a problem which lies in the source code of this repository

**Comment by hiyama283** [comment]
It is a matter of ideology, so it is up to you to leave the risk of not binded modules being called in your code.
Thank you.
