### ISSUE TITLE
Suggestion for the Zoot module

### ISSUE THREAD

**Issue by Powerstone10** [Sumandora/tarasande#19]
The Zoot module works really great but it would be really good if it also picks up the water that it has placed. I only recently started learning to code and I am no where near to understanding the code and because of that also not able to modify it.

**Comment by Sumandora** [comment]
This is already implemented but since the process of extinguishing yourself takes multiple ticks users commonly break the process by for example switching the slot, moving away from the water or in general just messing with the module. Not much I can do here.
